dist: trusty
language: node_js
notifications:
  email: false
node_js: lts/*
stages:
  - test
  - build
jobs:
  include:
    - stage: test
      name: 'Test ESLint Current'
      script:
        - npm run format:check
        - npm run test
    - stage: test
      name: 'Test ESLint v7'
      script:
        - npm i eslint@^7 @typescript-eslint/parser@^4 @typescript-eslint/eslint-plugin@^4
        - |
          cat package-lock.json | grep -A 1 \
            -e "\"eslint\": {" \
            -e "\"@typescript-eslint/parser\": {" \
            -e "\"@typescript-eslint/eslint-plugin\": {"
        - npm run test
    - stage: test
      name: 'Test ESLint v6'
      script:
        - npm i eslint@^6 @typescript-eslint/parser@^3 @typescript-eslint/eslint-plugin@^3
        - |
          cat package-lock.json | grep -A 1 \
            -e "\"eslint\": {" \
            -e "\"@typescript-eslint/parser\": {" \
            -e "\"@typescript-eslint/eslint-plugin\": {"
        - npm run test
    - stage: build
      name: 'Build and Release'
      script:
        - npm run build
      deploy:
        provider: script
        script: npm run semantic-release
        skip_cleanup: true
        keep_history: true
        on:
          tags: false
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(master|next)$
